name: CI

on: 
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Quality check with SonarCloud
      env:
        SONAR_TOKEN: c45c28c06af4a0fa2cad42fea7457ac4a075921d
      run: 
        mvn clean verify
        
    - name: Build with Maven
      run: mvn package