name: CI/CD

on: 
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
        
    - name: Quality check with SonarCloud
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      run: 
        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=juanitoxx_cardAPI
        
    - name: Build with Maven
      run: mvn package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.2.0
      with: 
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_TAG}}

  deploy_dev:
    name: Deploy to Dev Environment for PR
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.head_ref, 'dev/')
    
    steps:
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{secrets.RENDER_SERVICE_ID}}
        api-key: ${{secrets.RENDER_API_KEY }}

  deploy_prod:
    name: Deploy to Prod Environment for PR
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    
    steps:
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{secrets.RENDER_SERVICE_ID}}
        api-key: ${{secrets.RENDER_API_KEY }}


      
