name: CI/CD

on: 
  pull_request:
    branches: ["main"]


jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
        
    - name: Quality check with SonarCloud
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      run: 
        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=juanitoxx_cardAPI
        
    - name: Build with Maven
      run: mvn package
      
  deployment:
    runs-on: ubuntu-latest
    name: Deploy Job
    needs: build
    
    steps:
    - name:  Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.2.0
      with: 
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKER_TAG}}

    - name: Deploy to Render
      uses: sws2apps/render-deployment@v1.4.0
      with:
        apiKey: ${{secrets.RENDER_API_KEY }}
      

      
      
    
